# Generated by Django 5.1.1 on 2024-10-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_razorpay_order_id_payment_razorpay_order_id_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id_id',
            new_name='razorpay_order_id',
        ),
    ]
