# Generated by Django 5.1.1 on 2024-10-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_created_at_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
    ]
