# Generated by Django 5.1.1 on 2024-10-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_contact_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='names',
        ),
    ]
